# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: OpenFaaS build and push
      uses: mrsimpson/action-openfaas-build@0.3.0
      with:
        # The OpenFaaS function definition file
        stack-file: stack.yml
        # Your docker username with push authorization
        docker-username: ${{ secrets.DOCKER_LOGIN }}
        # Your docker password
        docker-password: ${{ secrets.DOCKER_PASS }}
        # Whether the built image shall be deployed (false=no, true=yes)
        deploy: true
        # OpenFaaS gateway URL (http(s)://my-public-gateway.tld)
        openfaas-gateway: ${{ secrets.OPENFAAS_GATEWAY }}
        # User for authenticating at OpenFaaS gateway
        openfaas-username: admin
        # Password for authenticating at OpenFaaS gateway
        openfaas-password: ${{ secrets.OPENFAAS_PASS }}
        
